categories:
  - title: "Features"
    label: "Feature"
  - title: "Breaking Change"
    label: "Breaking Change"
  - title: "Bug Fixes"
    label: "Bug"
  - title: "Documentation"
    label: "Documentation"
  - title: "Maintenance"
    label: "Maintenance"
change-template: "- $TITLE by @$AUTHOR (#$NUMBER)"
template: |
  ## New in frostbreak.org v$INPUT_VERSION

  $CHANGES
