name: "Deploy to Github Pages"
inputs:
  dist_path:
    required: true
    description: "Path to the directory containing the web artifact to deploy"
    default: "dist"
runs:
  using: "composite"
  steps:
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: ${{ inputs.dist_path }}
