name: CI
inputs:
  NODE_ENV:
    description: "Node environment"
    required: true
    default: staging

runs:
  using: "composite"
  steps:
    - name: Install dependencies
      run: npm ci
      shell: bash

    - name: Lint
      run: npm run lint
      shell: bash

    - name: Build
      run: npm run build:${{ inputs.NODE_ENV }}
      shell: bash

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        path: dist
        name: build
