name: Deploy PR preview

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
permissions:
  contents: write
  pull-requests: write
  pages: write

concurrency: preview-${{ github.ref }}

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install deps
        run: npm ci

        # If we use the CI action, the dist/__astro folder will be ignored by GH Jekyll.
        # Astro has their own action that makes a GH pages-friendly build output.
      - name: Build for GH Pages
        if: github.event.action != 'closed'
        uses: withastro/action@v4

      - name: Deploy preview
        id: deploy-preview
        uses: rossjrw/pr-preview-action@v1.6.1
        with:
          source-dir: ./dist
          token: ${{ github.token }}
