name: Deploy PR preview

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
permissions:
  contents: write
  pull-requests: write
  pages: write

concurrency: preview-${{ github.ref }}

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: CI
        uses: ./.github/actions/ci
        env:
          PR_PREVIEW_PREFIX: frostbreak.org/pr-preview/pr-${{ github.event.pull_request.number }}

      - name: Deploy preview
        id: deploy-preview
        uses: rossjrw/pr-preview-action@v1.6.1
        with:
          source-dir: dist
          token: ${{ github.token }}
